'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MiscReports

    '''<summary>
    '''ImageButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ImageButton2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButton2 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbQCYieldReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbQCYieldReport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbModifyLaserData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbModifyLaserData As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbInventoryReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbInventoryReport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbAcknowledgeFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAcknowledgeFile As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbRejectReport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRejectReport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbResponseFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbResponseFile As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbExtractLaserData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbExtractLaserData As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbACMLFile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbACMLFile As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbExtractLaserData0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbExtractLaserData0 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbExtractMuhlbauerData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbExtractMuhlbauerData As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbExtractMuhlbauerData0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbExtractMuhlbauerData0 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbExtractRejectCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbExtractRejectCard As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbDeliveryReceipt2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDeliveryReceipt2 As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbDeliveryReceiptManualExtraction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDeliveryReceiptManualExtraction As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbDR_PDF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDR_PDF As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbExtractCubaoBranchData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbExtractCubaoBranchData As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ASPxPopupControl1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPopupControl1 As Global.DevExpress.Web.ASPxPopupControl.ASPxPopupControl
End Class
